Update Aws-CA.yml

diff --git a/.github/workflows/Aws-CA.yml b/.github/workflows/Aws-CA.yml
--- a/.github/workflows/Aws-CA.yml
+++ b/.github/workflows/Aws-CA.yml
@@ -7,8 +7,10 @@ on:
 env:
   INSTANCE_ID: i-032407fb843e2ee2e
   REGION: us-west-1
-  DOMAIN: ca.nets.pp.ua
+  DOMAIN: 'ca.nets.pp.ua' # 需要查询的DNS名称
   CF_ZONE_ID: b2fc014bf87f67714afb1b9c10941a2e
+  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }} # 从GitHub Secrets中获取API Token
+  PROXIED: 'false' # 是否开启Cloudflare代理，默认否
 
 jobs:
   healthcheck_and_manage_ec2:
@@ -24,7 +26,7 @@ jobs:
     - name: Check Connectivity
       id: ping_check
       run: |
-        PING_OUTPUT=$(curl -sL https://v2.api-m.com/api/tcping?address=ca.nets.pp.ua&port=1081)
+        PING_OUTPUT=$(curl -sL https://v2.api-m.com/api/tcping?address=${{ env.DOMAIN }}&port=1081)
         if [[ $PING_OUTPUT == *"200"* ]]; then
           echo "Domain is pingable at $(date)"
           echo "::set-output name=pingable::true"
@@ -59,26 +61,47 @@ jobs:
         echo "New Public IP: $NEW_IP"
         echo "NEW_IP=$NEW_IP" >> $GITHUB_ENV
 
-    - name: Update Cloudflare DNS
-      if: steps.ping_check.outputs.pingable == 'false' && ${{ env.NEW_IP }} != ''
-      env:
-        CF_ZONE_ID: ${{ env.CF_ZONE_ID }}
-        CF_API_TOKEN: ${{ env.CF_API_TOKEN }}
-        DOMAIN: ${{ env.DOMAIN }}
-        NEW_IP: ${{ steps.get_new_public_ip.outputs.new_ip }}
+    - name: Get Cloudflare DNS Record ID
       run: |
-        echo "Updating Cloudflare DNS record for $DOMAIN to IP: $NEW_IP"
-        curl -X PUT "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/dns_records?name=$DOMAIN&type=A" \
-         -H "Authorization: Bearer $CF_API_TOKEN" \
-         -H "Content-Type: application/json" \
-         --data "{\"type\":\"A\",\"name\":\"$DOMAIN\",\"content\":\"$NEW_IP\",\"ttl\":120}"
+        # 使用cURL调用Cloudflare API获取DNS记录ID
+        DNS_RECORDS=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${{ env.CF_ZONE_ID }}/dns_records?name=${{ env.DOMAIN }}" \
+          -H "Authorization: Bearer ${{ env.CF_API_TOKEN }}" \
+          -H "Content-Type: application/json")
+        DNS_ID=$(echo "${DNS_RECORDS}" | jq -r '.result[] | select(.name == "'${{ env.DOMAIN }}'") | .id')
+        if [ -z "$DNS_ID" ]; then
+          echo "No DNS record found for ${{ env.DOMAIN }}"
+          exit 1
+        else
+          echo "DNS Record ID for ${{ env.DOMAIN }}: $DNS_ID"
+          echo "DNS_ID=$DNS_ID" >> $GITHUB_ENV
+        fi
 
+    - name: Update DNS Record
+      run: |
+        # 构建cURL请求命令，使用先前获取到的DNS_ID
+        UPDATE_CMD=$(echo -n "{\"type\":\"A\",\"name\":\"${{ env.DOMAIN }}\",\"content\":\"$NEW_IP\",\"proxied\":${{ env.PROXIED }}}")
+        curl -X PUT "https://api.cloudflare.com/client/v4/zones/${{ env.CF_ZONE_ID }}/dns_records/${{ env.DNS_ID }}" \
+          -H "Authorization: Bearer ${{ env.CF_API_TOKEN }}" \
+          -H "Content-Type: application/json" \
+          --data-raw "$UPDATE_CMD"
+
+        # 检查响应状态
+        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "https://api.cloudflare.com/client/v4/zones/${{ env.CF_ZONE_ID }}/dns_records/${{ env.DNS_ID }}" \
+          -H "Authorization: Bearer ${{ env.CF_API_TOKEN }}" \
+          -H "Content-Type: application/json")
+
+        if [ "$RESPONSE" -eq 200 ]; then
+          echo "DNS record updated successfully."
+        else
+          echo "Failed to update DNS record. Response code: $RESPONSE"
+          exit 1
+        fi
     - name: Log to Console and Send Bark Notification
       if: always()
       env:
-        BARK_PUSH_URL: 'https://api.day.app/oZaeqGLJzRLSxW7dJqeACn/AWS'
+        BARK_PUSH_URL: 'https://api.day.app/oZaeqGLJzRLSxW7dJqeACn'
       run: |
-        MESSAGE="Status: ${{ steps.ping_check.outputs.pingable }}, IP: ${{ steps.get_new_public_ip.outputs.new_ip }}"
+        MESSAGE="Status: ${{ steps.ping_check.outputs.pingable }}, IP: $NEW_IP"
         echo "Logging: $MESSAGE"
         # 发送Bark通知，确保BARK_PUSH_URL已替换为实际的URL
         curl -X POST -H "Content-type: application/json" -d "{\"text\":\"$MESSAGE\"}" $BARK_PUSH_URL
