Update GCP HK.yml

diff --git a/.github/workflows/GCP HK.yml b/.github/workflows/GCP HK.yml
--- a/.github/workflows/GCP HK.yml
+++ b/.github/workflows/GCP HK.yml
@@ -13,9 +13,10 @@ jobs:
       TARGET_PORT: 1081
       GCP_VM_ZONE: 'asia-east2-a'
       GCP_VM_NAME: 'instance-hk'
-      CLOUDFLARE_DOMAIN: 'hk.nets.pp.ua'
-      CLOUDFLARE_ZONE_ID: b2fc014bf87f67714afb1b9c10941a2e
+      DOMAIN: 'hk.nets.pp.ua'
+      CF_ZONE_ID: b2fc014bf87f67714afb1b9c10941a2e
       GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
+      PROXIED: 'false' # 是否开启Cloudflare代理，默认否
 
     steps:
     - name: Check Domain Connectivity
@@ -54,15 +55,43 @@ jobs:
         instance_ip=$(gcloud compute instances describe ${{ env.GCP_VM_NAME }} --zone ${{ env.GCP_VM_ZONE }} --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
         echo "INSTANCE_IP=$instance_ip" >> $GITHUB_ENV
 
-    - name: Update Cloudflare DNS
-      if: env.REACHABLE == 'false' && env.INSTANCE_IP
+    - name: Get Cloudflare DNS Record ID
+      if: env.REACHABLE == 'false'
       run: |
-        # 使用Cloudflare API更新DNS记录
-        curl -X PUT "https://api.cloudflare.com/client/v4/zones/${{ env.CLOUDFLARE_ZONE_ID }}/dns_records" \
-          -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
+        # 使用cURL调用Cloudflare API获取DNS记录ID
+        DNS_RECORDS=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${{ env.CF_ZONE_ID }}/dns_records?name=${{ env.DOMAIN }}" \
+          -H "Authorization: Bearer ${{ env.CF_API_TOKEN }}" \
+          -H "Content-Type: application/json")
+        DNS_ID=$(echo "${DNS_RECORDS}" | jq -r '.result[] | select(.name == "'${{ env.DOMAIN }}'") | .id')
+        if [ -z "$DNS_ID" ]; then
+          echo "No DNS record found for ${{ env.DOMAIN }}"
+          exit 1
+        else
+          echo "DNS Record ID for ${{ env.DOMAIN }}: $DNS_ID"
+          echo "DNS_ID=$DNS_ID" >> $GITHUB_ENV
+        fi
+
+    - name: Update DNS Record
+      if: env.REACHABLE == 'false'
+      run: |
+        # 构建cURL请求命令，使用先前获取到的DNS_ID
+        UPDATE_CMD=$(echo -n "{\"type\":\"A\",\"name\":\"${{ env.DOMAIN }}\",\"content\":\"$INSTANCE_IP\",\"proxied\":${{ env.PROXIED }}}")
+        curl -X PUT "https://api.cloudflare.com/client/v4/zones/${{ env.CF_ZONE_ID }}/dns_records/${{ env.DNS_ID }}" \
+          -H "Authorization: Bearer ${{ env.CF_API_TOKEN }}" \
           -H "Content-Type: application/json" \
-          --data "{\"type\":\"A\",\"name\":\"${{ env.CLOUDFLARE_DOMAIN }}\",\"content\":\"${{ env.INSTANCE_IP }}\",\"ttl\":120}" \
-          --fail
+          --data-raw "$UPDATE_CMD"
+
+        # 检查响应状态
+        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "https://api.cloudflare.com/client/v4/zones/${{ env.CF_ZONE_ID }}/dns_records/${{ env.DNS_ID }}" \
+          -H "Authorization: Bearer ${{ env.CF_API_TOKEN }}" \
+          -H "Content-Type: application/json")
+
+        if [ "$RESPONSE" -eq 200 ]; then
+          echo "DNS record updated successfully."
+        else
+          echo "Failed to update DNS record. Response code: $RESPONSE"
+          exit 1
+        fi
 
     - name: Log Summary
       if: always()
