Update IP Management Pro.yml

diff --git a/.github/workflows/IP Management Pro.yml b/.github/workflows/IP Management Pro.yml
--- a/.github/workflows/IP Management Pro.yml
+++ b/.github/workflows/IP Management Pro.yml
@@ -5,76 +5,102 @@ on:
   #  - cron: '0 */3 * * *' # 每3小时运行一次
   workflow_dispatch:
 
+env:
+  GCP_PROJECT_ID: skillful-cider-440305-d7
+  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_025 }}
+  CF_ZONE_ID: 1fa9774064820f53fe1733e37a19f721
+  PORT: 1081
+  PROXIED: 'false'
+  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
+
 jobs:
-  setup:
+  read_config:
     runs-on: ubuntu-latest
     outputs:
-      domain0: ${{ steps.set-env.outputs.domain0 }}
-      gcp_vm_name0: ${{ steps.set-env.outputs.gcp_vm_name0 }}
-      gcp_vm_zone0: ${{ steps.set-env.outputs.gcp_vm_zone0 }}
-      gcp_region0: ${{ steps.set-env.outputs.gcp_region0 }}
-      # Repeat for other servers if needed
-
+      server_list: ${{ steps.set-server-list.outputs.server_list }}
     steps:
     - name: Checkout Repository
       uses: actions/checkout@v2
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.x'
-
-    - name: Install PyYAML
-      run: pip install pyyaml
-
-    - name: Parse YAML and set environment variables
-      id: set-env
+    - name: Read and Parse Server Config
+      id: set-server-list
       run: |
-        python parse_yaml.py
-        echo "::set-output name=domain0::$(echo $DOMAIN_0)"
-        echo "::set-output name=gcp_vm_name0::$(echo $GCP_VM_NAME_0)"
-        echo "::set-output name=gcp_vm_zone0::$(echo $GCP_VM_ZONE_0)"
-        echo "::set-output name=gcp_region0::$(echo $GCP_REGION_0)"
-        # Repeat for other servers if needed
+        server_list=$(cat servers.txt | tr '\n' ',' | sed 's/,$//')
+        echo "Server list: $server_list"  # 添加日志记录
+        if [ -z "$server_list" ]; then
+          echo "Error: Server list is empty or invalid."
+          exit 1
+        fi
+        echo "server_list=$server_list" >> $GITHUB_OUTPUT
 
   ip_management:
-    needs: setup
+    needs: read_config
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        server: ${{ fromJson(format('[{}]', replace(needs.read_config.outputs.server_list, ',', '","')))}}
 
     steps:
     - name: Checkout Repository
       uses: actions/checkout@v2
 
-    - name: Authentication
-      uses: google-github-actions/auth@v2
-      with:
-        credentials_json: '${{ secrets.GCP_SA_KEY }}'
+    - name: Debug Output
+      run: |
+        echo "Server list from read_config: ${{ needs.read_config.outputs.server_list }}"
+        if [ -z "${{ needs.read_config.outputs.server_list }}" ]; then
+          echo "Error: Server list is empty or invalid."
+          exit 1
+        fi
+        parsed_server_list=$(echo "${{ needs.read_config.outputs.server_list }}" | tr ',' '\n')
+        echo "Parsed server list: $parsed_server_list"
+        if [ -z "$parsed_server_list" ]; then
+          echo "Error: Parsed server list is empty or invalid."
+          exit 1
+        fi
 
-    - name: Set up Cloud SDK
-      uses: google-github-actions/setup-gcloud@v2
-
-    - name: Use gcloud CLI
-      run: gcloud info
+    - name: Load Server Config
+      id: load-server-config
+      run: |
+        IFS=':' read -r DOMAIN GCP_VM_NAME GCP_REGION GCP_VM_ZONE <<< "${{ matrix.server }}"
+        echo "DOMAIN=$DOMAIN" >> $GITHUB_ENV
+        echo "GCP_VM_NAME=$GCP_VM_NAME" >> $GITHUB_ENV
+        echo "GCP_VM_ZONE=$GCP_VM_ZONE" >> $GITHUB_ENV
+        echo "GCP_REGION=$GCP_REGION" >> $GITHUB_ENV
 
     - name: Check Domain Connectivity
       id: check-connectivity
       run: |
-        API_URL="https://api.jaxing.cc/v2/Tcping?host=${{needs.setup.outputs.domain0}}&port=${{env.PORT}}"
+        API_URL="https://api.jaxing.cc/v2/Tcping?host=${{ env.DOMAIN }}&port=${{ env.PORT }}"
         response=$(curl -sL $API_URL)
-        echo "Response for domain ${{needs.setup.outputs.domain0}}: $response"
+        echo "Response for domain ${{ env.DOMAIN }}: $response"
         if [[ $response == *'"msg":"请求成功"'* ]] && ! echo "$response" | grep -q '"dial tcp'; then
-          echo "Domain ${{needs.setup.outputs.domain0}} is reachable."
+          echo "Domain ${{ env.DOMAIN }} is reachable."
           echo "REACHABLE=true" >> $GITHUB_ENV
         else
-          echo "Domain ${{needs.setup.outputs.domain0}} is unreachable."
+          echo "Domain ${{ env.DOMAIN }} is unreachable."
           echo "REACHABLE=false" >> $GITHUB_ENV
         fi
+
+    - name: Authentication
+      id: auth
+      if: env.REACHABLE == 'false'
+      uses: google-github-actions/auth@v2
+      with:
+        credentials_json: '${{ env.GCP_SA_KEY }}'
+
+    - name: Set up Cloud SDK
+      if: env.REACHABLE == 'false'
+      uses: google-github-actions/setup-gcloud@v2
+
+    - name: Use gcloud CLI
+      if: env.REACHABLE == 'false'
+      run: gcloud info
 
     - name: Get Current VM External IP
       if: env.REACHABLE == 'false'
       id: get_current_ip
       run: |
-        CURRENT_IP=$(gcloud compute instances describe ${{ env[format('GCP_VM_NAME_{0}', matrix.server_index)] }} --zone=${{ env[format('GCP_VM_ZONE_{0}', matrix.server_index)] }} --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
+        CURRENT_IP=$(gcloud compute instances describe ${{ env.GCP_VM_NAME }} --zone=${{ env.GCP_VM_ZONE }} --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
         echo "Current IP is $CURRENT_IP"
         echo "CURRENT_IP=$CURRENT_IP" >> $GITHUB_ENV
 
@@ -84,9 +110,9 @@ jobs:
       run: |
         retry_count=0
         max_retries=5
-        vm_name=${{ env[format('GCP_VM_NAME_{0}', matrix.server_index)] }}
-        vm_zone=${{ env[format('GCP_VM_ZONE_{0}', matrix.server_index)] }}
-        region=${{ env[format('GCP_REGION_{0}', matrix.server_index)] }}
+        vm_name=${{ env.GCP_VM_NAME }}
+        vm_zone=${{ env.GCP_VM_ZONE }}
+        region=${{ env.GCP_REGION }}
         static_ips=()
         while (( retry_count < max_retries )); do
             CURRENT_IP=$(gcloud compute instances describe $vm_name --zone=$vm_zone --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
@@ -124,7 +150,7 @@ jobs:
         DNS_RECORDS=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${{ env.CF_ZONE_ID }}/dns_records?name=${{ env.DOMAIN }}" \
           -H "Authorization: Bearer ${{ env.CF_API_TOKEN }}" \
           -H "Content-Type: application/json")
-        DNS_ID=$(echo "${DNS_RECORDS}" | jq -r '.result[] | select(.name == "${{ env.DOMAIN }}") | .id')
+        DNS_ID=$(echo "${DNS_RECORDS}" | jq -r '.result[] | select(.name == "'${{ env.DOMAIN }}'") | .id')
         if [ -z "$DNS_ID" ]; then
           echo "No DNS record found for ${{ env.DOMAIN }}"
           exit 1
@@ -132,6 +158,7 @@ jobs:
           echo "DNS Record ID for ${{ env.DOMAIN }}: $DNS_ID"
           echo "DNS_ID=$DNS_ID" >> $GITHUB_ENV
         fi
+
     - name: Update DNS Record
       if: env.REACHABLE == 'false'
       run: |
