Update QA_GCP HK设置静态 IP 并获取新 IP.yml

diff --git a/.github/workflows/QA_GCP HK设置静态 IP 并获取新 IP.yml b/.github/workflows/QA_GCP HK设置静态 IP 并获取新 IP.yml
--- a/.github/workflows/QA_GCP HK设置静态 IP 并获取新 IP.yml
+++ b/.github/workflows/QA_GCP HK设置静态 IP 并获取新 IP.yml
@@ -4,16 +4,37 @@ on:
   workflow_dispatch:
 
 env:
-  instance_name: instance-hk
-  zone: asia-east2-a
   GCP_PROJECT_ID: infra-falcon-424407-c7
   GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
+  GCP_VM_ZONE: 'asia-east2-a'
+  GCP_VM_NAME: 'instance-hk'
+  DOMAIN: 'hk.nets.pp.ua'
+  CF_ZONE_ID: b2fc014bf87f67714afb1b9c10941a2e
+  PORT: 1081
+  PROXIED: 'false' # 是否开启Cloudflare代理，默认否
+  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }} # 从GitHub Secrets中获取API Token
 
 jobs:
   ip_management:
     runs-on: ubuntu-latest
     steps:
+    - name: Check Domain Connectivity
+      id: check-connectivity
+      run: |
+        # 使用curl获取ping结果
+        API_URL="https://v2.api-m.com/api/tcping?address=${{env.DOMAIN}}&port=${{env.PORT}}"
+        response=$(curl -sL $API_URL)
+        echo ${{ env.DOMAIN }} $response
+        if [[ "$response" == *"200"* ]]; then
+          echo "Domain $Domain is reachable."
+          echo "REACHABLE=true" >> $GITHUB_ENV
+        else
+          echo "Domain $Domain is unreachable."
+          echo "REACHABLE=false" >> $GITHUB_ENV
+        fi
+        
     - name: Checkout Repository
+      if: env.REACHABLE == 'false'
       uses: actions/checkout@v2
 
     - id: 'auth'
@@ -22,12 +43,15 @@ jobs:
         credentials_json: '${{ secrets.GCP_SA_KEY }}'
 
     - name: 'Set up Cloud SDK'
+      if: env.REACHABLE == 'false'
       uses: 'google-github-actions/setup-gcloud@v2'
 
     - name: 'Use gcloud CLI'
+      if: env.REACHABLE == 'false'
       run: 'gcloud info'
 
     - name: Setup Google Cloud SDK
+      if: env.REACHABLE == 'false'
       uses: google-github-actions/setup-gcloud@v2.1.0
       with:
         project_id: ${{ env.GCP_PROJECT_ID }}
@@ -35,9 +59,10 @@ jobs:
         export_default_credentials: true
 
     - name: Get Current VM External IP
+      if: env.REACHABLE == 'false'
       id: get_current_ip
       run: |
-        CURRENT_IP=$(gcloud compute instances describe "${{ env.instance_name }}" --zone="${{ env.zone }}" --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
+        CURRENT_IP=$(gcloud compute instances describe "${{ env.GCP_VM_name }}" --zone="${{ env.GCP_VM_zone }}" --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
         echo "::set-output name=current_ip::$CURRENT_IP"
         echo "Current IP is $CURRENT_IP"
         
@@ -45,9 +70,9 @@ jobs:
       id: reconfig_vm_and_test_ip
       run: |
         while true; do
-            gcloud compute instances delete-access-config ${{ env.instance_name }} --access-config-name="external-nat" --zone=${{ env.zone }}
+            gcloud compute instances delete-access-config ${{ env.GCP_VM_name }} --access-config-name="external-nat" --zone=${{ env.GCP_VM_zone }}
             while true; do
-                STATUS=$(gcloud compute instances describe "${{ env.instance_name }}" --zone="${{ env.zone }}" --project="${{ env.GCP_PROJECT_ID }}" --format='value(status)')
+                STATUS=$(gcloud compute instances describe "${{ env.GCP_VM_name }}" --zone="${{ env.GCP_VM_zone }}" --project="${{ env.GCP_PROJECT_ID }}" --format='value(status)')
                 if [ "$STATUS" = "RUNNING" ]; then
                     echo "instance is running..."
                     break
@@ -55,8 +80,8 @@ jobs:
                 echo "Waiting for instance to be running..."
                 sleep 10
             done
-            gcloud compute instances add-access-config ${{ env.instance_name }} --zone=${{ env.zone }}
-            NEW_IP=$(gcloud compute instances describe "${{ env.instance_name }}" --zone="${{ env.zone }}" --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
+            gcloud compute instances add-access-config ${{ env.GCP_VM_name }} --zone=${{ env.GCP_VM_zone }}
+            NEW_IP=$(gcloud compute instances describe "${{ env.GCP_VM_name }}" --zone="${{ env.GCP_VM_zone }}" --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
             echo "::set-output name=new_ip::$NEW_IP"
             echo "New IP is $NEW_IP"
             API_URL="https://v2.api-m.com/api/tcping?address=$NEW_IP&port=1081"
@@ -64,9 +89,60 @@ jobs:
             echo $NEW_IP $response
             if [[ "$response" == *"200"* ]]; then
               echo "$NEW_IP is OK to Ping..."
+              echo "NEW_IP=$new_ip" >> $GITHUB_ENV
               break
             fi
             echo "$NEW_IP is NOT OK to Ping, VM Reconfiging..."
             sleep 10
          done
+
+    - name: Get Cloudflare DNS Record ID
+      if: env.REACHABLE == 'false'
+      run: |
+        # 使用cURL调用Cloudflare API获取DNS记录ID
+        DNS_RECORDS=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${{ env.CF_ZONE_ID }}/dns_records?name=${{ env.DOMAIN }}" \
+          -H "Authorization: Bearer ${{ env.CF_API_TOKEN }}" \
+          -H "Content-Type: application/json")
+        DNS_ID=$(echo "${DNS_RECORDS}" | jq -r '.result[] | select(.name == "'${{ env.DOMAIN }}'") | .id')
+        if [ -z "$DNS_ID" ]; then
+          echo "No DNS record found for ${{ env.DOMAIN }}"
+          exit 1
+        else
+          echo "DNS Record ID for ${{ env.DOMAIN }}: $DNS_ID"
+          echo "DNS_ID=$DNS_ID" >> $GITHUB_ENV
+        fi
+
+    - name: Update DNS Record
+      if: env.REACHABLE == 'false'
+      run: |
+        # 构建cURL请求命令，使用先前获取到的DNS_ID
+        UPDATE_CMD=$(echo -n "{\"type\":\"A\",\"name\":\"${{ env.DOMAIN }}\",\"content\":\"$INSTANCE_IP\",\"proxied\":${{ env.PROXIED }}}")
+        curl -X PUT "https://api.cloudflare.com/client/v4/zones/${{ env.CF_ZONE_ID }}/dns_records/${{ env.DNS_ID }}" \
+          -H "Authorization: Bearer ${{ env.CF_API_TOKEN }}" \
+          -H "Content-Type: application/json" \
+          --data-raw "$UPDATE_CMD"
+
+        # 检查响应状态
+        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "https://api.cloudflare.com/client/v4/zones/${{ env.CF_ZONE_ID }}/dns_records/${{ env.DNS_ID }}" \
+          -H "Authorization: Bearer ${{ env.CF_API_TOKEN }}" \
+          -H "Content-Type: application/json")
+
+        if [ "$RESPONSE" -eq 200 ]; then
+          echo "DNS record updated successfully."
+        else
+          echo "Failed to update DNS record. Response code: $RESPONSE"
+          exit 1
+        fi
+
+    - name: Log Summary
+      if: always()
+      run: |
+        if [ "${{ env.REACHABLE }}" == 'true' ]; then
+          echo "Summary: Domain was reachable. No action taken."
+        elif [ -n "${{ env.INSTANCE_IP }}" ]; then
+          echo "Summary: DNS record updated to ${{ env.INSTANCE_IP }} after instance restart."
+        else
+          echo "Summary: Unexpected error occurred. No DNS update performed."
+        fi
+
          
